// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRunningProcess(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CheckRunningProcess'](arg1, arg2, arg3, arg4);
}

export function Create(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['Create'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteApp(arg1) {
  return window['go']['backend']['App']['DeleteApp'](arg1);
}

export function FindAll() {
  return window['go']['backend']['App']['FindAll']();
}

export function FindMostPlayedGame() {
  return window['go']['backend']['App']['FindMostPlayedGame']();
}

export function FindOne(arg1) {
  return window['go']['backend']['App']['FindOne'](arg1);
}

export function FindTotalGamesPlayedLastWeek(arg1, arg2) {
  return window['go']['backend']['App']['FindTotalGamesPlayedLastWeek'](arg1, arg2);
}

export function FindTotalTimePlayed() {
  return window['go']['backend']['App']['FindTotalTimePlayed']();
}

export function FindTotalTimePlayedByGameThisWeek(arg1, arg2, arg3) {
  return window['go']['backend']['App']['FindTotalTimePlayedByGameThisWeek'](arg1, arg2, arg3);
}

export function FindTotalTimePlayedByGameToday(arg1, arg2, arg3) {
  return window['go']['backend']['App']['FindTotalTimePlayedByGameToday'](arg1, arg2, arg3);
}

export function FindTotalTimePlayedLastMonth(arg1, arg2) {
  return window['go']['backend']['App']['FindTotalTimePlayedLastMonth'](arg1, arg2);
}

export function FindTotalTimePlayedLastWeek(arg1, arg2) {
  return window['go']['backend']['App']['FindTotalTimePlayedLastWeek'](arg1, arg2);
}

export function FindTotalTimePlayedLastYear(arg1, arg2) {
  return window['go']['backend']['App']['FindTotalTimePlayedLastYear'](arg1, arg2);
}

export function FindTotalTimePlayedToday(arg1, arg2) {
  return window['go']['backend']['App']['FindTotalTimePlayedToday'](arg1, arg2);
}

export function GameExePath() {
  return window['go']['backend']['App']['GameExePath']();
}

export function HowlongtobeatRequest(arg1) {
  return window['go']['backend']['App']['HowlongtobeatRequest'](arg1);
}

export function Pcspecs() {
  return window['go']['backend']['App']['Pcspecs']();
}

export function Play(arg1, arg2) {
  return window['go']['backend']['App']['Play'](arg1, arg2);
}

export function TimePlayedByDayThisWeek(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['backend']['App']['TimePlayedByDayThisWeek'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function Update(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['Update'](arg1, arg2, arg3, arg4);
}
