// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindTotalTimePlayed() {
  return window['go']['main']['App']['FindTotalTimePlayed']()
}

export function FindTotalTimePlayedGameToday(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindTotalTimePlayedGameToday'](
    arg1,
    arg2,
    arg3,
  )
}

export function FindTotalTimePlayedLastWeek(arg1, arg2) {
  return window['go']['main']['App']['FindTotalTimePlayedLastWeek'](arg1, arg2)
}

export function FindTotalTimePlayedLastYear(arg1, arg2) {
  return window['go']['main']['App']['FindTotalTimePlayedLastYear'](arg1, arg2)
}

export function FindTotalTimePlayedToday(arg1, arg2) {
  return window['go']['main']['App']['FindTotalTimePlayedToday'](arg1, arg2)
}

export function CheckRunningProcess(arg1, arg2, arg3, arg4) {
  window['go']['main']['App']['CheckRunningProcess'](arg1, arg2, arg3, arg4)
}

export function FindAll() {
  return window['go']['main']['App']['FindAll']()
}

export function FindMostPlayedGame() {
  return window['go']['main']['App']['FindMostPlayedGame']()
}

export function Update(arg1, arg2, arg3, arg4) {
  window['go']['main']['App']['Update'](arg1, arg2, arg3, arg4)
}

export function GameExePath() {
  return window['go']['main']['App']['GameExePath']()
}

export function Play(arg1, arg2) {
  window['go']['main']['App']['Play'](arg1, arg2)
}

export function FindTotalTimePlayedLastMonth(arg1, arg2) {
  return window['go']['main']['App']['FindTotalTimePlayedLastMonth'](arg1, arg2)
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1)
}

export function Pcspecs() {
  return window['go']['main']['App']['Pcspecs']()
}

export function FindTotalTimePlayedGameThisWeek(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindTotalTimePlayedGameThisWeek'](
    arg1,
    arg2,
    arg3,
  )
}

export function HowlongtobeatRequest(arg1) {
  return window['go']['main']['App']['HowlongtobeatRequest'](arg1)
}

export function Create(arg1, arg2, arg3, arg4, arg5) {
  window['go']['main']['App']['Create'](arg1, arg2, arg3, arg4, arg5)
}

export function DeleteApp(arg1) {
  window['go']['main']['App']['DeleteApp'](arg1)
}

export function FindTotalGamesPlayedLastWeek(arg1, arg2) {
  return window['go']['main']['App']['FindTotalGamesPlayedLastWeek'](arg1, arg2)
}
